// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversestructuresstructureid

type Output struct {
	Name          string    `json:"name"`
	OwnerId       int64     `json:"owner_id"`
	Position      *Position `json:"position"`
	SolarSystemId int64     `json:"solar_system_id"`
	TypeId        *int64    `json:"type_id"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
