// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversestructuresstructureid

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](http.MethodGet, "/universe/structures/{structure_id}")
