// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidstandings

type Output struct {
	FromId   int64   `json:"from_id"`
	FromType string  `json:"from_type"`
	Standing float64 `json:"standing"`
}
