// Code generated by cmd/generate-request; DO NOT EDIT.

package getfleetsfleetidmembers

import (
	"time"
)

type Output struct {
	CharacterId    int64     `json:"character_id"`
	JoinTime       time.Time `json:"join_time"`
	Role           string    `json:"role"`
	RoleName       string    `json:"role_name"`
	ShipTypeId     int64     `json:"ship_type_id"`
	SolarSystemId  int64     `json:"solar_system_id"`
	SquadId        int64     `json:"squad_id"`
	StationId      *int64    `json:"station_id"`
	TakesFleetWarp bool      `json:"takes_fleet_warp"`
	WingId         int64     `json:"wing_id"`
}
