// Code generated by cmd/generate-request; DO NOT EDIT.

package getfleetsfleetidmembers

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](http.MethodGet, "/fleets/{fleet_id}/members")
