// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridmail

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Character    character.Identifier `path:"character_id"`
	ApprovedCost *int64               `body:"json"`
	Body         string               `body:"json"`
	Recipients   []Recipients         `body:"json"`
	Subject      string               `body:"json"`
}

type Recipients struct {
	RecipientId   int64  `json:"recipient_id"`
	RecipientType string `json:"recipient_type"`
}
