// Code generated by cmd/generate-request; DO NOT EDIT.

package postuiopenwindownewmail

type Input struct {
	Body               string  `body:"json"`
	Recipients         []int64 `body:"json"`
	Subject            string  `body:"json"`
	ToCorpOrAllianceId *int64  `body:"json"`
	ToMailingListId    *int64  `body:"json"`
}
