// Code generated by cmd/generate-request; DO NOT EDIT.

package getfleetsfleetid

type Output struct {
	IsFreeMove     bool   `json:"is_free_move"`
	IsRegistered   bool   `json:"is_registered"`
	IsVoiceEnabled bool   `json:"is_voice_enabled"`
	Motd           string `json:"motd"`
}
