// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidstarbases

import (
	"time"
)

type Output struct {
	MoonId          *int64     `json:"moon_id"`
	OnlinedSince    *time.Time `json:"onlined_since"`
	ReinforcedUntil *time.Time `json:"reinforced_until"`
	StarbaseId      int64      `json:"starbase_id"`
	State           *string    `json:"state"`
	SystemId        int64      `json:"system_id"`
	TypeId          int64      `json:"type_id"`
	UnanchorAt      *time.Time `json:"unanchor_at"`
}
