// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversestarsstarid

type Output struct {
	Age           int64   `json:"age"`
	Luminosity    float64 `json:"luminosity"`
	Name          string  `json:"name"`
	Radius        int64   `json:"radius"`
	SolarSystemId int64   `json:"solar_system_id"`
	SpectralClass string  `json:"spectral_class"`
	Temperature   int64   `json:"temperature"`
	TypeId        int64   `json:"type_id"`
}
