// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidindustryjobs

import (
	"github.com/xaroth/lib-esi-go/common/corporation"
)

type Input struct {
	Corporation      corporation.Identifier `path:"corporation_id"`
	IncludeCompleted *bool                  `query:"include_completed"`
	Page             *int32                 `query:"page"`
}
