// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidindustryjobs

import (
	"time"
)

type Output struct {
	ActivityId           int64      `json:"activity_id"`
	BlueprintId          int64      `json:"blueprint_id"`
	BlueprintLocationId  int64      `json:"blueprint_location_id"`
	BlueprintTypeId      int64      `json:"blueprint_type_id"`
	CompletedCharacterId *int64     `json:"completed_character_id"`
	CompletedDate        *time.Time `json:"completed_date"`
	Cost                 *float64   `json:"cost"`
	Duration             int64      `json:"duration"`
	EndDate              time.Time  `json:"end_date"`
	FacilityId           int64      `json:"facility_id"`
	InstallerId          int64      `json:"installer_id"`
	JobId                int64      `json:"job_id"`
	LicensedRuns         *int64     `json:"licensed_runs"`
	LocationId           int64      `json:"location_id"`
	OutputLocationId     int64      `json:"output_location_id"`
	PauseDate            *time.Time `json:"pause_date"`
	Probability          *float64   `json:"probability"`
	ProductTypeId        *int64     `json:"product_type_id"`
	Runs                 int64      `json:"runs"`
	StartDate            time.Time  `json:"start_date"`
	Status               string     `json:"status"`
	SuccessfulRuns       *int64     `json:"successful_runs"`
}
