// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidalliancehistory

import (
	"time"
)

type Output struct {
	AllianceId *int64    `json:"alliance_id"`
	IsDeleted  *bool     `json:"is_deleted"`
	RecordId   int64     `json:"record_id"`
	StartDate  time.Time `json:"start_date"`
}
