// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniverseregionsregionid

type Output struct {
	Constellations []int64 `json:"constellations"`
	Description    *string `json:"description"`
	Name           string  `json:"name"`
	RegionId       int64   `json:"region_id"`
}
