// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridskills

type Output struct {
	Skills        []CharactersSkillsSkill `json:"skills"`
	TotalSp       int64                   `json:"total_sp"`
	UnallocatedSp *int64                  `json:"unallocated_sp"`
}

type CharactersSkillsSkill struct {
	ActiveSkillLevel   int64 `json:"active_skill_level"`
	SkillId            int64 `json:"skill_id"`
	SkillpointsInSkill int64 `json:"skillpoints_in_skill"`
	TrainedSkillLevel  int64 `json:"trained_skill_level"`
}
