// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmining

type Output struct {
	Date          string `json:"date"`
	Quantity      int64  `json:"quantity"`
	SolarSystemId int64  `json:"solar_system_id"`
	TypeId        int64  `json:"type_id"`
}
