// Code generated by cmd/generate-request; DO NOT EDIT.

package getdogmaeffectseffectid

type Output struct {
	Description              *string     `json:"description"`
	DisallowAutoRepeat       *bool       `json:"disallow_auto_repeat"`
	DischargeAttributeId     *int64      `json:"discharge_attribute_id"`
	DisplayName              *string     `json:"display_name"`
	DurationAttributeId      *int64      `json:"duration_attribute_id"`
	EffectCategory           *int64      `json:"effect_category"`
	EffectId                 int64       `json:"effect_id"`
	ElectronicChance         *bool       `json:"electronic_chance"`
	FalloffAttributeId       *int64      `json:"falloff_attribute_id"`
	IconId                   *int64      `json:"icon_id"`
	IsAssistance             *bool       `json:"is_assistance"`
	IsOffensive              *bool       `json:"is_offensive"`
	IsWarpSafe               *bool       `json:"is_warp_safe"`
	Modifiers                []Modifiers `json:"modifiers"`
	Name                     *string     `json:"name"`
	PostExpression           *int64      `json:"post_expression"`
	PreExpression            *int64      `json:"pre_expression"`
	Published                *bool       `json:"published"`
	RangeAttributeId         *int64      `json:"range_attribute_id"`
	RangeChance              *bool       `json:"range_chance"`
	TrackingSpeedAttributeId *int64      `json:"tracking_speed_attribute_id"`
}

type Modifiers struct {
	Domain               *string `json:"domain"`
	EffectId             *int64  `json:"effect_id"`
	Func                 string  `json:"func"`
	ModifiedAttributeId  *int64  `json:"modified_attribute_id"`
	ModifyingAttributeId *int64  `json:"modifying_attribute_id"`
	Operator             *int64  `json:"operator"`
}
