// Code generated by cmd/generate-request; DO NOT EDIT.

package postuniversenames

type Output struct {
	Category string `json:"category"`
	Id       int64  `json:"id"`
	Name     string `json:"name"`
}
