// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridclones

import (
	"time"
)

type Output struct {
	HomeLocation          *HomeLocation `json:"home_location"`
	JumpClones            []JumpClones  `json:"jump_clones"`
	LastCloneJumpDate     *time.Time    `json:"last_clone_jump_date"`
	LastStationChangeDate *time.Time    `json:"last_station_change_date"`
}

type HomeLocation struct {
	LocationId   *int64  `json:"location_id"`
	LocationType *string `json:"location_type"`
}

type JumpClones struct {
	Implants     []int64 `json:"implants"`
	JumpCloneId  int64   `json:"jump_clone_id"`
	LocationId   int64   `json:"location_id"`
	LocationType string  `json:"location_type"`
	Name         *string `json:"name"`
}
