// Code generated by cmd/generate-request; DO NOT EDIT.

package getparagonhubskinralliances

import (
	"github.com/xaroth/lib-esi-go/common/alliance"
)

type Input struct {
	After    *string             `query:"after"`
	Before   *string             `query:"before"`
	Limit    *int64              `query:"limit"`
	Alliance alliance.Identifier `path:"alliance_id"`
}
