// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversesystemssystemid

type Output struct {
	ConstellationId int64     `json:"constellation_id"`
	Name            string    `json:"name"`
	Planets         []Planets `json:"planets"`
	Position        Position  `json:"position"`
	SecurityClass   *string   `json:"security_class"`
	SecurityStatus  float64   `json:"security_status"`
	StarId          *int64    `json:"star_id"`
	Stargates       []int64   `json:"stargates"`
	Stations        []int64   `json:"stations"`
	SystemId        int64     `json:"system_id"`
}

type Planets struct {
	AsteroidBelts []int64 `json:"asteroid_belts"`
	Moons         []int64 `json:"moons"`
	PlanetId      int64   `json:"planet_id"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
