// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersmercenarytacticaloperationslisting

import (
	"github.com/xaroth/lib-esi-go/common/item"
	"github.com/xaroth/lib-esi-go/common/uuid"
)

type Output struct {
	Operations []CharactersMercenaryTacticalOperationsListingOperation `json:"operations"`
}

type CharactersMercenaryTacticalOperationsListingOperation struct {
	Id           uuid.UUID       `json:"id"`
	MercenaryDen item.Identifier `json:"mercenary_den_id"`
}
