// Code generated by cmd/generate-request; DO NOT EDIT.

package getdogmaattributesattributeid

type Output struct {
	AttributeId  int64    `json:"attribute_id"`
	DefaultValue *float64 `json:"default_value"`
	Description  *string  `json:"description"`
	DisplayName  *string  `json:"display_name"`
	HighIsGood   *bool    `json:"high_is_good"`
	IconId       *int64   `json:"icon_id"`
	Name         *string  `json:"name"`
	Published    *bool    `json:"published"`
	Stackable    *bool    `json:"stackable"`
	UnitId       *int64   `json:"unit_id"`
}
