// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridroles

type Output struct {
	Roles        []string `json:"roles"`
	RolesAtBase  []string `json:"roles_at_base"`
	RolesAtHq    []string `json:"roles_at_hq"`
	RolesAtOther []string `json:"roles_at_other"`
}
