// Code generated by cmd/generate-request; DO NOT EDIT.

package putfleetsfleetidmembersmemberid

type Input struct {
	FleetId  int64  `path:"fleet_id"`
	MemberId int64  `path:"member_id"`
	Role     string `body:"json"`
	SquadId  *int64 `body:"json"`
	WingId   *int64 `body:"json"`
}
