// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationcorporationidminingobservers

type Output struct {
	LastUpdated  string `json:"last_updated"`
	ObserverId   int64  `json:"observer_id"`
	ObserverType string `json:"observer_type"`
}
