// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontractscontractidbids

import (
	"time"
)

type Output struct {
	Amount   float64   `json:"amount"`
	BidId    int64     `json:"bid_id"`
	BidderId int64     `json:"bidder_id"`
	DateBid  time.Time `json:"date_bid"`
}
