// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontractscontractidbids

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](http.MethodGet, "/corporations/{corporation_id}/contracts/{contract_id}/bids")
