// Code generated by cmd/generate-request; DO NOT EDIT.

package getmarketsprices

type Output struct {
	AdjustedPrice *float64 `json:"adjusted_price"`
	AveragePrice  *float64 `json:"average_price"`
	TypeId        int64    `json:"type_id"`
}
