// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridagentsresearch

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
}
