// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridagentsresearch

import (
	"time"
)

type Output struct {
	AgentId         int64     `json:"agent_id"`
	PointsPerDay    float64   `json:"points_per_day"`
	RemainderPoints float64   `json:"remainder_points"`
	SkillTypeId     int64     `json:"skill_type_id"`
	StartedAt       time.Time `json:"started_at"`
}
