// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversemoonsmoonid

type Output struct {
	MoonId   int64    `json:"moon_id"`
	Name     string   `json:"name"`
	Position Position `json:"position"`
	SystemId int64    `json:"system_id"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
