// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidicons

type Output struct {
	Px128x128 *string `json:"px128x128"`
	Px256x256 *string `json:"px256x256"`
	Px64x64   *string `json:"px64x64"`
}
