// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcontractscontractiditems

type Output struct {
	IsIncluded  bool   `json:"is_included"`
	IsSingleton bool   `json:"is_singleton"`
	Quantity    int64  `json:"quantity"`
	RawQuantity *int64 `json:"raw_quantity"`
	RecordId    int64  `json:"record_id"`
	TypeId      int64  `json:"type_id"`
}
