// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcontractscontractiditems

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](http.MethodGet, "/characters/{character_id}/contracts/{contract_id}/items")
