// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridfittings

type Output struct {
	Description string  `json:"description"`
	FittingId   int64   `json:"fitting_id"`
	Items       []Items `json:"items"`
	Name        string  `json:"name"`
	ShipTypeId  int64   `json:"ship_type_id"`
}

type Items struct {
	Flag     string `json:"flag"`
	Quantity int64  `json:"quantity"`
	TypeId   int64  `json:"type_id"`
}
