// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationcorporationidminingobserversobserverid

type Output struct {
	CharacterId           int64  `json:"character_id"`
	LastUpdated           string `json:"last_updated"`
	Quantity              int64  `json:"quantity"`
	RecordedCorporationId int64  `json:"recorded_corporation_id"`
	TypeId                int64  `json:"type_id"`
}
