// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidmedalsissued

import (
	"time"
)

type Output struct {
	CharacterId int64     `json:"character_id"`
	IssuedAt    time.Time `json:"issued_at"`
	IssuerId    int64     `json:"issuer_id"`
	MedalId     int64     `json:"medal_id"`
	Reason      string    `json:"reason"`
	Status      string    `json:"status"`
}
