// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationid

import (
	"time"

	"github.com/xaroth/lib-esi-go/common/alliance"
	"github.com/xaroth/lib-esi-go/common/character"
	"github.com/xaroth/lib-esi-go/common/faction"
	"github.com/xaroth/lib-esi-go/common/station"
)

type Output struct {
	Alliance    *alliance.Identifier `json:"alliance_id"`
	Ceo         character.Identifier `json:"ceo_id"`
	Creator     character.Identifier `json:"creator_id"`
	DateFounded *time.Time           `json:"date_founded"`
	Description *string              `json:"description"`
	Faction     *faction.Identifier  `json:"faction_id"`
	HomeStation *station.Identifier  `json:"home_station_id"`
	MemberCount int64                `json:"member_count"`
	Name        string               `json:"name"`
	Shares      *int64               `json:"shares"`
	TaxRate     float64              `json:"tax_rate"`
	Ticker      string               `json:"ticker"`
	Url         *string              `json:"url"`
	WarEligible *bool                `json:"war_eligible"`
}
