// Code generated by cmd/generate-request; DO NOT EDIT.

package postuniverseids

type Output struct {
	Agents         []Agents         `json:"agents"`
	Alliances      []Alliances      `json:"alliances"`
	Characters     []Characters     `json:"characters"`
	Constellations []Constellations `json:"constellations"`
	Corporations   []Corporations   `json:"corporations"`
	Factions       []Factions       `json:"factions"`
	InventoryTypes []InventoryTypes `json:"inventory_types"`
	Regions        []Regions        `json:"regions"`
	Stations       []Stations       `json:"stations"`
	Systems        []Systems        `json:"systems"`
}

type Agents struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Alliances struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Characters struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Constellations struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Corporations struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Factions struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type InventoryTypes struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Regions struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Stations struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}

type Systems struct {
	Id   *int64  `json:"id"`
	Name *string `json:"name"`
}
