// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridfleet

type Output struct {
	FleetBossId int64  `json:"fleet_boss_id"`
	FleetId     int64  `json:"fleet_id"`
	Role        string `json:"role"`
	SquadId     int64  `json:"squad_id"`
	WingId      int64  `json:"wing_id"`
}
