// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversestationsstationid

type Output struct {
	MaxDockableShipVolume    float64  `json:"max_dockable_ship_volume"`
	Name                     string   `json:"name"`
	OfficeRentalCost         float64  `json:"office_rental_cost"`
	Owner                    *int64   `json:"owner"`
	Position                 Position `json:"position"`
	RaceId                   *int64   `json:"race_id"`
	ReprocessingEfficiency   float64  `json:"reprocessing_efficiency"`
	ReprocessingStationsTake float64  `json:"reprocessing_stations_take"`
	Services                 []string `json:"services"`
	StationId                int64    `json:"station_id"`
	SystemId                 int64    `json:"system_id"`
	TypeId                   int64    `json:"type_id"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
