// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersfreelancejobsparticipation

import (
	"github.com/xaroth/lib-esi-go/common/character"
	"github.com/xaroth/lib-esi-go/common/uuid"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	JobId     uuid.UUID            `path:"job_id"`
}
