// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmedals

import (
	"time"
)

type Output struct {
	CorporationId int64      `json:"corporation_id"`
	Date          time.Time  `json:"date"`
	Description   string     `json:"description"`
	Graphics      []Graphics `json:"graphics"`
	IssuerId      int64      `json:"issuer_id"`
	MedalId       int64      `json:"medal_id"`
	Reason        string     `json:"reason"`
	Status        string     `json:"status"`
	Title         string     `json:"title"`
}

type Graphics struct {
	Color   *int64 `json:"color"`
	Graphic string `json:"graphic"`
	Layer   int64  `json:"layer"`
	Part    int64  `json:"part"`
}
