// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmedals

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](http.MethodGet, "/characters/{character_id}/medals")
