// Code generated by cmd/generate-request; DO NOT EDIT.

package getmetaname

type Output struct {
	Current string          `json:"current"`
	History []MetaNameEntry `json:"history"`
}

type MetaNameEntry struct {
	Date string `json:"date"`
	Name string `json:"name"`
}
