// Code generated by cmd/generate-request; DO NOT EDIT.

package getsovereigntymap

type Output struct {
	AllianceId    *int64 `json:"alliance_id"`
	CorporationId *int64 `json:"corporation_id"`
	FactionId     *int64 `json:"faction_id"`
	SystemId      int64  `json:"system_id"`
}
