package commonmodels

import (
	"encoding/json"
	"fmt"
	"go/format"
	"strconv"
)

const generatedBy = "// Code generated by cmd/generate-common-models; DO NOT EDIT.\n\n"

// GeneratePackage returns formatted main and test source (test may be nil).
func GeneratePackage(m Model, modulePath, importBase string) (mainGo []byte, testGo []byte, err error) {
	var src string
	switch {
	case m.Schema.Type == "integer" && m.Schema.Format == "int64":
		src, err = renderInt64ID(m)
	case m.Schema.Type == "string" && m.Schema.Format == "uuid":
		src, err = renderStringAlias(m)
	case m.Schema.Type == "string" && m.Schema.Format == "date":
		src, err = renderStringAlias(m)
	case m.Schema.Type == "string" && len(m.Schema.Enum) > 0:
		src, err = renderEnum(m, modulePath)
	default:
		return nil, nil, fmt.Errorf("%s: unsupported common model shape type=%q format=%q", m.SchemaName, m.Schema.Type, m.Schema.Format)
	}
	if err != nil {
		return nil, nil, err
	}

	mainGo, err = format.Source([]byte(generatedBy + src))
	if err != nil {
		return nil, nil, fmt.Errorf("%s: format main: %w", m.SchemaName, err)
	}

	if len(m.Examples) == 0 {
		return mainGo, nil, nil
	}

	testSrc, err := renderTest(m, modulePath, importBase)
	if err != nil {
		return nil, nil, err
	}
	testGo, err = format.Source([]byte(testSrc))
	if err != nil {
		return nil, nil, fmt.Errorf("%s: format test: %w", m.SchemaName, err)
	}
	return mainGo, testGo, nil
}

func renderInt64ID(m Model) (string, error) {
	return ExecuteTemplate("int64", m)
}

func renderStringAlias(m Model) (string, error) {
	return ExecuteTemplate("string_alias", m)
}

func renderEnum(m Model, modulePath string) (string, error) {
	enum := m.Schema.Enum
	descs := m.Schema.XEnumDescriptions
	if len(descs) > 0 && len(descs) != len(enum) {
		return "", fmt.Errorf("%s: x-enum-descriptions length %d != enum length %d", m.SchemaName, len(descs), len(enum))
	}

	fields := make([]enumFieldData, 0, len(enum))
	seen := make(map[string]bool)
	for i, raw := range enum {
		wire, ok := raw.(string)
		if !ok {
			return "", fmt.Errorf("%s: enum[%d] is not a string", m.SchemaName, i)
		}
		desc := ""
		if i < len(descs) {
			desc = descs[i]
		}
		field := EnumFieldName(wire, desc)
		if field == "" || seen[field] {
			field = fmt.Sprintf("Value%d", i)
		}
		seen[field] = true
		fields = append(fields, enumFieldData{Name: field, WireValue: wire})
	}

	return ExecuteTemplate("enum", enumTemplateData{
		Package:    m.Package,
		TypeName:   m.TypeName,
		VarName:    enumVarName(m.SchemaName),
		ModulePath: modulePath,
		Fields:     fields,
	})
}

func enumVarName(schemaName string) string {
	if endsWithLowercaseID(schemaName) {
		return "Values"
	}
	return schemaName
}

func renderTest(m Model, modulePath, importBase string) (string, error) {
	importPath := modulePath + "/" + importBase + "/" + m.Package
	qualifiedType := m.Package + "." + m.TypeName

	cases := make([]testCaseData, 0, len(m.Examples))
	for i, ex := range m.Examples {
		inputJSON, wantConv, err := exampleToTest(m, ex)
		if err != nil {
			return "", err
		}
		cases = append(cases, testCaseData{
			TypeName:      m.TypeName,
			Index:         i,
			InputJSON:     inputJSON,
			QualifiedType: qualifiedType,
			WantConv:      wantConv,
		})
	}

	return ExecuteTemplate("test", testTemplateData{
		TestPackage: m.Package + "_test",
		ImportPath:  importPath,
		Cases:       cases,
	})
}

func exampleToTest(m Model, ex any) (inputJSON, wantConv string, err error) {
	qualifiedType := m.Package + "." + m.TypeName
	switch {
	case m.Schema.Type == "integer" && m.Schema.Format == "int64":
		n, err := toInt64(ex)
		if err != nil {
			return "", "", err
		}
		return "`" + strconv.FormatInt(n, 10) + "`", fmt.Sprintf("%s(%d)", qualifiedType, n), nil
	case m.Schema.Type == "string":
		s, ok := ex.(string)
		if !ok {
			return "", "", fmt.Errorf("expected string example, got %T", ex)
		}
		b, err := json.Marshal(s)
		if err != nil {
			return "", "", err
		}
		return "`" + string(b) + "`", fmt.Sprintf("%s(%s)", qualifiedType, strconv.Quote(string(s))), nil
	default:
		return "", "", fmt.Errorf("unsupported test example type")
	}
}

func toInt64(ex any) (int64, error) {
	switch v := ex.(type) {
	case float64:
		return int64(v), nil
	case json.Number:
		return v.Int64()
	case int64:
		return v, nil
	case int:
		return int64(v), nil
	default:
		return 0, fmt.Errorf("expected numeric example, got %T", ex)
	}
}
