// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidroles

type Output struct {
	CharacterId           int64    `json:"character_id"`
	GrantableRoles        []string `json:"grantable_roles"`
	GrantableRolesAtBase  []string `json:"grantable_roles_at_base"`
	GrantableRolesAtHq    []string `json:"grantable_roles_at_hq"`
	GrantableRolesAtOther []string `json:"grantable_roles_at_other"`
	Roles                 []string `json:"roles"`
	RolesAtBase           []string `json:"roles_at_base"`
	RolesAtHq             []string `json:"roles_at_hq"`
	RolesAtOther          []string `json:"roles_at_other"`
}
