// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversefactions

type Output struct {
	CorporationId        *int64  `json:"corporation_id"`
	Description          string  `json:"description"`
	FactionId            int64   `json:"faction_id"`
	IsUnique             bool    `json:"is_unique"`
	MilitiaCorporationId *int64  `json:"militia_corporation_id"`
	Name                 string  `json:"name"`
	SizeFactor           float64 `json:"size_factor"`
	SolarSystemId        *int64  `json:"solar_system_id"`
	StationCount         int64   `json:"station_count"`
	StationSystemCount   int64   `json:"station_system_count"`
}
