// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridonline

import (
	"time"
)

type Output struct {
	LastLogin  *time.Time `json:"last_login"`
	LastLogout *time.Time `json:"last_logout"`
	Logins     *int64     `json:"logins"`
	Online     bool       `json:"online"`
}
