// Code generated by cmd/generate-request; DO NOT EDIT.

package putfleetsfleetidwingswingid

type Input struct {
	FleetId int64  `path:"fleet_id"`
	WingId  int64  `path:"wing_id"`
	Name    string `body:"json"`
}
