// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridblueprints

type Output struct {
	ItemId             int64  `json:"item_id"`
	LocationFlag       string `json:"location_flag"`
	LocationId         int64  `json:"location_id"`
	MaterialEfficiency int64  `json:"material_efficiency"`
	Quantity           int64  `json:"quantity"`
	Runs               int64  `json:"runs"`
	TimeEfficiency     int64  `json:"time_efficiency"`
	TypeId             int64  `json:"type_id"`
}
