// Code generated by cmd/generate-request; DO NOT EDIT.

package postfleetsfleetidmembers

type Input struct {
	FleetId     int64  `path:"fleet_id"`
	CharacterId int64  `body:"json" required:"true"`
	Role        string `body:"json" required:"true"`
	SquadId     *int64 `body:"json"`
	WingId      *int64 `body:"json"`
}
