// Code generated by cmd/generate-request; DO NOT EDIT.

package postfleetsfleetidmembers

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](http.MethodPost, "/fleets/{fleet_id}/members")
