// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersparagonhubskinr

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	After     *string              `query:"after"`
	Before    *string              `query:"before"`
	Limit     *int64               `query:"limit"`
	Character character.Identifier `path:"character_id"`
}
