// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmaillists

type Output struct {
	MailingListId int64  `json:"mailing_list_id"`
	Name          string `json:"name"`
}
