// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversesystemkills

type Output struct {
	NpcKills  int64 `json:"npc_kills"`
	PodKills  int64 `json:"pod_kills"`
	ShipKills int64 `json:"ship_kills"`
	SystemId  int64 `json:"system_id"`
}
