// Code generated by cmd/generate-request; DO NOT EDIT.

package getindustrysystems

type Output struct {
	CostIndices   []CostIndices `json:"cost_indices"`
	SolarSystemId int64         `json:"solar_system_id"`
}

type CostIndices struct {
	Activity  string  `json:"activity"`
	CostIndex float64 `json:"cost_index"`
}
