// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridnotifications

import (
	"time"
)

type Output struct {
	IsRead         *bool     `json:"is_read"`
	NotificationId int64     `json:"notification_id"`
	SenderId       int64     `json:"sender_id"`
	SenderType     string    `json:"sender_type"`
	Text           *string   `json:"text"`
	Timestamp      time.Time `json:"timestamp"`
	Type           string    `json:"type"`
}
