// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcontactslabels

type Output struct {
	LabelId   int64  `json:"label_id"`
	LabelName string `json:"label_name"`
}
