// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontainerslogs

import (
	"time"
)

type Output struct {
	Action           string    `json:"action"`
	CharacterId      int64     `json:"character_id"`
	ContainerId      int64     `json:"container_id"`
	ContainerTypeId  int64     `json:"container_type_id"`
	LocationFlag     string    `json:"location_flag"`
	LocationId       int64     `json:"location_id"`
	LoggedAt         time.Time `json:"logged_at"`
	NewConfigBitmask *int64    `json:"new_config_bitmask"`
	OldConfigBitmask *int64    `json:"old_config_bitmask"`
	PasswordType     *string   `json:"password_type"`
	Quantity         *int64    `json:"quantity"`
	TypeId           *int64    `json:"type_id"`
}
