// Code generated by cmd/generate-request; DO NOT EDIT.

package postfleetsfleetidwingswingidsquads

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](http.MethodPost, "/fleets/{fleet_id}/wings/{wing_id}/squads")
