// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharactersstructuresmercenarydensdetail

import (
	"github.com/xaroth/lib-esi-go/common/character"
	"github.com/xaroth/lib-esi-go/common/item"
)

type Input struct {
	MercenaryDen item.Identifier      `path:"mercenary_den_id"`
	Character    character.Identifier `path:"character_id"`
}
