// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidkillmailsrecent

type Output struct {
	KillmailHash string `json:"killmail_hash"`
	KillmailId   int64  `json:"killmail_id"`
}
