// Code generated by cmd/generate-request; DO NOT EDIT.

package postuiautopilotwaypoint

type Input struct {
	AddToBeginning      bool  `query:"add_to_beginning"`
	ClearOtherWaypoints bool  `query:"clear_other_waypoints"`
	DestinationId       int64 `query:"destination_id"`
}
