// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscosmeticsskinr

type Output struct {
	Licenses []CharactersCosmeticsSkinrItem `json:"licenses"`
}

type CharactersCosmeticsSkinrItem struct {
	Activated   bool   `json:"activated"`
	SkinrId     string `json:"skinr_id"`
	Unactivated int64  `json:"unactivated"`
}
