// Code generated by cmd/generate-request; DO NOT EDIT.

package getwarswarid

import (
	"time"
)

type Output struct {
	Aggressor     Aggressor  `json:"aggressor"`
	Allies        []Allies   `json:"allies"`
	Declared      time.Time  `json:"declared"`
	Defender      Defender   `json:"defender"`
	Finished      *time.Time `json:"finished"`
	Id            int64      `json:"id"`
	Mutual        bool       `json:"mutual"`
	OpenForAllies bool       `json:"open_for_allies"`
	Retracted     *time.Time `json:"retracted"`
	Started       *time.Time `json:"started"`
}

type Aggressor struct {
	AllianceId    *int64  `json:"alliance_id"`
	CorporationId *int64  `json:"corporation_id"`
	IskDestroyed  float64 `json:"isk_destroyed"`
	ShipsKilled   int64   `json:"ships_killed"`
}

type Allies struct {
	AllianceId    *int64 `json:"alliance_id"`
	CorporationId *int64 `json:"corporation_id"`
}

type Defender struct {
	AllianceId    *int64  `json:"alliance_id"`
	CorporationId *int64  `json:"corporation_id"`
	IskDestroyed  float64 `json:"isk_destroyed"`
	ShipsKilled   int64   `json:"ships_killed"`
}
