// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridnotificationscontacts

import (
	"time"
)

type Output struct {
	Message           string    `json:"message"`
	NotificationId    int64     `json:"notification_id"`
	SendDate          time.Time `json:"send_date"`
	SenderCharacterId int64     `json:"sender_character_id"`
	StandingLevel     float64   `json:"standing_level"`
}
