// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharactersaffiliation

type Output struct {
	AllianceId    *int64 `json:"alliance_id"`
	CharacterId   int64  `json:"character_id"`
	CorporationId int64  `json:"corporation_id"`
	FactionId     *int64 `json:"faction_id"`
}
