// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcontracts

import (
	"time"
)

type Output struct {
	AcceptorId          int64      `json:"acceptor_id"`
	AssigneeId          int64      `json:"assignee_id"`
	Availability        string     `json:"availability"`
	Buyout              *float64   `json:"buyout"`
	Collateral          *float64   `json:"collateral"`
	ContractId          int64      `json:"contract_id"`
	DateAccepted        *time.Time `json:"date_accepted"`
	DateCompleted       *time.Time `json:"date_completed"`
	DateExpired         time.Time  `json:"date_expired"`
	DateIssued          time.Time  `json:"date_issued"`
	DaysToComplete      *int64     `json:"days_to_complete"`
	EndLocationId       *int64     `json:"end_location_id"`
	ForCorporation      bool       `json:"for_corporation"`
	IssuerCorporationId int64      `json:"issuer_corporation_id"`
	IssuerId            int64      `json:"issuer_id"`
	Price               *float64   `json:"price"`
	Reward              *float64   `json:"reward"`
	StartLocationId     *int64     `json:"start_location_id"`
	Status              string     `json:"status"`
	Title               *string    `json:"title"`
	Type                string     `json:"type"`
	Volume              *float64   `json:"volume"`
}
