// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversegraphicsgraphicid

type Output struct {
	CollisionFile *string `json:"collision_file"`
	GraphicFile   *string `json:"graphic_file"`
	GraphicId     int64   `json:"graphic_id"`
	IconFolder    *string `json:"icon_folder"`
	SofDna        *string `json:"sof_dna"`
	SofFationName *string `json:"sof_fation_name"`
	SofHullName   *string `json:"sof_hull_name"`
	SofRaceName   *string `json:"sof_race_name"`
}
