// Code generated by cmd/generate-request; DO NOT EDIT.

package getinsuranceprices

type Output struct {
	Levels []Levels `json:"levels"`
	TypeId int64    `json:"type_id"`
}

type Levels struct {
	Cost   float64 `json:"cost"`
	Name   string  `json:"name"`
	Payout float64 `json:"payout"`
}
