// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidstructures

import (
	"time"
)

type Output struct {
	CorporationId      int64      `json:"corporation_id"`
	FuelExpires        *time.Time `json:"fuel_expires"`
	Name               *string    `json:"name"`
	NextReinforceApply *time.Time `json:"next_reinforce_apply"`
	NextReinforceHour  *int64     `json:"next_reinforce_hour"`
	ProfileId          int64      `json:"profile_id"`
	ReinforceHour      *int64     `json:"reinforce_hour"`
	Services           []Services `json:"services"`
	State              string     `json:"state"`
	StateTimerEnd      *time.Time `json:"state_timer_end"`
	StateTimerStart    *time.Time `json:"state_timer_start"`
	StructureId        int64      `json:"structure_id"`
	SystemId           int64      `json:"system_id"`
	TypeId             int64      `json:"type_id"`
	UnanchorsAt        *time.Time `json:"unanchors_at"`
}

type Services struct {
	Name  string `json:"name"`
	State string `json:"state"`
}
