// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridplanetsplanetid

import (
	"time"
)

type Output struct {
	Links  []Links  `json:"links"`
	Pins   []Pins   `json:"pins"`
	Routes []Routes `json:"routes"`
}

type Links struct {
	DestinationPinId int64 `json:"destination_pin_id"`
	LinkLevel        int64 `json:"link_level"`
	SourcePinId      int64 `json:"source_pin_id"`
}

type Contents struct {
	Amount int64 `json:"amount"`
	TypeId int64 `json:"type_id"`
}

type Heads struct {
	HeadId    int64   `json:"head_id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type ExtractorDetails struct {
	CycleTime     *int64   `json:"cycle_time"`
	HeadRadius    *float64 `json:"head_radius"`
	Heads         []Heads  `json:"heads"`
	ProductTypeId *int64   `json:"product_type_id"`
	QtyPerCycle   *int64   `json:"qty_per_cycle"`
}

type FactoryDetails struct {
	SchematicId int64 `json:"schematic_id"`
}

type Pins struct {
	Contents         []Contents        `json:"contents"`
	ExpiryTime       *time.Time        `json:"expiry_time"`
	ExtractorDetails *ExtractorDetails `json:"extractor_details"`
	FactoryDetails   *FactoryDetails   `json:"factory_details"`
	InstallTime      *time.Time        `json:"install_time"`
	LastCycleStart   *time.Time        `json:"last_cycle_start"`
	Latitude         float64           `json:"latitude"`
	Longitude        float64           `json:"longitude"`
	PinId            int64             `json:"pin_id"`
	SchematicId      *int64            `json:"schematic_id"`
	TypeId           int64             `json:"type_id"`
}

type Routes struct {
	ContentTypeId    int64   `json:"content_type_id"`
	DestinationPinId int64   `json:"destination_pin_id"`
	Quantity         float64 `json:"quantity"`
	RouteId          int64   `json:"route_id"`
	SourcePinId      int64   `json:"source_pin_id"`
	Waypoints        []int64 `json:"waypoints"`
}
