// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniverseraces

type Output struct {
	AllianceId  int64  `json:"alliance_id"`
	Description string `json:"description"`
	Name        string `json:"name"`
	RaceId      int64  `json:"race_id"`
}
