// Code generated by cmd/generate-request; DO NOT EDIT.

package getmetastatus

type Output struct {
	Routes []MetaStatusRoute `json:"routes"`
}

type MetaStatusRoute struct {
	Method string `json:"method"`
	Path   string `json:"path"`
	Status string `json:"status"`
}
