// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationcorporationidminingextractions

import (
	"time"
)

type Output struct {
	ChunkArrivalTime    time.Time `json:"chunk_arrival_time"`
	ExtractionStartTime time.Time `json:"extraction_start_time"`
	MoonId              int64     `json:"moon_id"`
	NaturalDecayTime    time.Time `json:"natural_decay_time"`
	StructureId         int64     `json:"structure_id"`
}
