// Code generated by cmd/generate-request; DO NOT EDIT.

package putcharacterscharacteridcalendareventid

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](http.MethodPut, "/characters/{character_id}/calendar/{event_id}")
