// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcalendar

import (
	"time"
)

type Output struct {
	EventDate     *time.Time `json:"event_date"`
	EventId       *int64     `json:"event_id"`
	EventResponse *string    `json:"event_response"`
	Importance    *int64     `json:"importance"`
	Title         *string    `json:"title"`
}
