// Code generated by cmd/generate-request; DO NOT EDIT.

package getsovereigntystructures

import (
	"time"
)

type Output struct {
	AllianceId                  int64      `json:"alliance_id"`
	SolarSystemId               int64      `json:"solar_system_id"`
	StructureId                 int64      `json:"structure_id"`
	StructureTypeId             int64      `json:"structure_type_id"`
	VulnerabilityOccupancyLevel *float64   `json:"vulnerability_occupancy_level"`
	VulnerableEndTime           *time.Time `json:"vulnerable_end_time"`
	VulnerableStartTime         *time.Time `json:"vulnerable_start_time"`
}
