// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidcustomsoffices

type Output struct {
	AllianceTaxRate          *float64 `json:"alliance_tax_rate"`
	AllowAccessWithStandings bool     `json:"allow_access_with_standings"`
	AllowAllianceAccess      bool     `json:"allow_alliance_access"`
	BadStandingTaxRate       *float64 `json:"bad_standing_tax_rate"`
	CorporationTaxRate       *float64 `json:"corporation_tax_rate"`
	ExcellentStandingTaxRate *float64 `json:"excellent_standing_tax_rate"`
	GoodStandingTaxRate      *float64 `json:"good_standing_tax_rate"`
	NeutralStandingTaxRate   *float64 `json:"neutral_standing_tax_rate"`
	OfficeId                 int64    `json:"office_id"`
	ReinforceExitEnd         int64    `json:"reinforce_exit_end"`
	ReinforceExitStart       int64    `json:"reinforce_exit_start"`
	StandingLevel            *string  `json:"standing_level"`
	SystemId                 int64    `json:"system_id"`
	TerribleStandingTaxRate  *float64 `json:"terrible_standing_tax_rate"`
	TypeId                   *int64   `json:"type_id"`
}
