// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversegroupsgroupid

type Output struct {
	CategoryId int64   `json:"category_id"`
	GroupId    int64   `json:"group_id"`
	Name       string  `json:"name"`
	Published  bool    `json:"published"`
	Types      []int64 `json:"types"`
}
