// Code generated by cmd/generate-request; DO NOT EDIT.

package getindustryfacilities

type Output struct {
	FacilityId    int64    `json:"facility_id"`
	OwnerId       int64    `json:"owner_id"`
	RegionId      int64    `json:"region_id"`
	SolarSystemId int64    `json:"solar_system_id"`
	Tax           *float64 `json:"tax"`
	TypeId        int64    `json:"type_id"`
}
