// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniverseancestries

type Output struct {
	BloodlineId      int64   `json:"bloodline_id"`
	Description      string  `json:"description"`
	IconId           *int64  `json:"icon_id"`
	Id               int64   `json:"id"`
	Name             string  `json:"name"`
	ShortDescription *string `json:"short_description"`
}
