// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidmedals

import (
	"time"
)

type Output struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatorId   int64     `json:"creator_id"`
	Description string    `json:"description"`
	MedalId     int64     `json:"medal_id"`
	Title       string    `json:"title"`
}
