// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridassetsnames

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	Body      []int64              `body:"json"`
}
