// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidstarbasesstarbaseid

type Output struct {
	AllowAllianceMembers                bool     `json:"allow_alliance_members"`
	AllowCorporationMembers             bool     `json:"allow_corporation_members"`
	Anchor                              string   `json:"anchor"`
	AttackIfAtWar                       bool     `json:"attack_if_at_war"`
	AttackIfOtherSecurityStatusDropping bool     `json:"attack_if_other_security_status_dropping"`
	AttackSecurityStatusThreshold       *float64 `json:"attack_security_status_threshold"`
	AttackStandingThreshold             *float64 `json:"attack_standing_threshold"`
	FuelBayTake                         string   `json:"fuel_bay_take"`
	FuelBayView                         string   `json:"fuel_bay_view"`
	Fuels                               []Fuels  `json:"fuels"`
	Offline                             string   `json:"offline"`
	Online                              string   `json:"online"`
	Unanchor                            string   `json:"unanchor"`
	UseAllianceStandings                bool     `json:"use_alliance_standings"`
}

type Fuels struct {
	Quantity int64 `json:"quantity"`
	TypeId   int64 `json:"type_id"`
}
