package requestgen

import (
	"fmt"
	"go/format"
)

const generatedBy = "// Code generated by cmd/generate-request; DO NOT EDIT.\n\n"

// GeneratedFiles holds formatted source for one operation package.
type GeneratedFiles struct {
	Input  []byte // nil if static
	Output []byte
	Request []byte
}

// GeneratePackage renders input.go, output.go, and request.go.
func GeneratePackage(m PackageModel, cfg Config) (GeneratedFiles, error) {
	var out GeneratedFiles
	var err error

	if !m.Static {
		inFields := append(m.InputFields, allStructFields(m.InputNested)...)
		commonIn, otherIn := fileImportsForFields(inFields, cfg, fieldsNeedTime(inFields))
		src, err := executeTemplate("input.go.tmpl", fileTemplateData{
			PackageName:   m.PackageName,
			RootName:      "Input",
			CommonImports: commonIn,
			OtherImports:  otherIn,
			HasImports:    len(commonIn)+len(otherIn) > 0,
			Fields:        m.InputFields,
			Nested:        m.InputNested,
		})
		if err != nil {
			return out, err
		}
		out.Input, err = formatGeneratedGo(cfg, generatedBy+src)
		if err != nil {
			return out, fmt.Errorf("format input: %w", err)
		}
	}

	if !m.NoOutputFile {
		var outSrc string
		var err error
		if m.OutputAlias != "" {
			aliasFields := []StructField{{Type: m.OutputAliasGoType}}
			commonOut, otherOut := fileImportsForFields(aliasFields, cfg, fieldsNeedTime(aliasFields))
			outSrc, err = executeTemplate("output_alias.go.tmpl", outputAliasTemplateData{
				PackageName:   m.PackageName,
				AliasType:     m.OutputAlias,
				CommonImports: commonOut,
				OtherImports:  otherOut,
				HasImports:    len(commonOut)+len(otherOut) > 0,
			})
		} else {
			outFields := append(m.OutputFields, allStructFields(m.OutputNested)...)
			commonOut, otherOut := fileImportsForFields(outFields, cfg, fieldsNeedTime(outFields))
			outSrc, err = executeTemplate("output.go.tmpl", fileTemplateData{
				PackageName:   m.PackageName,
				RootName:      "Output",
				CommonImports: commonOut,
				OtherImports:  otherOut,
				HasImports:    len(commonOut)+len(otherOut) > 0,
				Fields:        m.OutputFields,
				Nested:        m.OutputNested,
			})
		}
		if err != nil {
			return out, err
		}
		out.Output, err = formatGeneratedGo(cfg, generatedBy+outSrc)
		if err != nil {
			return out, fmt.Errorf("format output: %w", err)
		}
	}

	reqSrc, err := executeTemplate("request.go.tmpl", requestTemplateData{
		PackageName:   m.PackageName,
		RequestImport: cfg.requestImport(),
		MethodConst:   methodConstFixed(m.Method),
		PathLiteral:   pathLiteral(m.Path),
		OutputType:    m.OutputType,
		Static:        m.Static,
	})
	if err != nil {
		return out, err
	}
	out.Request, err = format.Source([]byte(generatedBy + reqSrc))
	if err != nil {
		return out, fmt.Errorf("format request: %w", err)
	}

	return out, nil
}

func formatGeneratedGo(cfg Config, src string) ([]byte, error) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, err
	}
	return groupImportBlockInSource(formatted, cfg), nil
}
