// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniverseschematicsschematicid

type Output struct {
	CycleTime     int64  `json:"cycle_time"`
	SchematicName string `json:"schematic_name"`
}
