// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversestargatesstargateid

type Output struct {
	Destination Destination `json:"destination"`
	Name        string      `json:"name"`
	Position    Position    `json:"position"`
	StargateId  int64       `json:"stargate_id"`
	SystemId    int64       `json:"system_id"`
	TypeId      int64       `json:"type_id"`
}

type Destination struct {
	StargateId int64 `json:"stargate_id"`
	SystemId   int64 `json:"system_id"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
