// Code generated by cmd/generate-request; DO NOT EDIT.

package getloyaltystorescorporationidoffers

type Output struct {
	AkCost        *int64          `json:"ak_cost"`
	IskCost       int64           `json:"isk_cost"`
	LpCost        int64           `json:"lp_cost"`
	OfferId       int64           `json:"offer_id"`
	Quantity      int64           `json:"quantity"`
	RequiredItems []RequiredItems `json:"required_items"`
	TypeId        int64           `json:"type_id"`
}

type RequiredItems struct {
	Quantity int64 `json:"quantity"`
	TypeId   int64 `json:"type_id"`
}
