// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridlocation

type Output struct {
	SolarSystemId int64  `json:"solar_system_id"`
	StationId     *int64 `json:"station_id"`
	StructureId   *int64 `json:"structure_id"`
}
