// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectscontributors

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](http.MethodGet, "/corporations/{corporation_id}/projects/{project_id}/contributors")
