// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniverseplanetsplanetid

type Output struct {
	Name     string   `json:"name"`
	PlanetId int64    `json:"planet_id"`
	Position Position `json:"position"`
	SystemId int64    `json:"system_id"`
	TypeId   int64    `json:"type_id"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
