// Code generated by cmd/generate-common-models; DO NOT EDIT.

package race

import "strconv"

type Identifier int64

func (id Identifier) String() string {
	return strconv.FormatInt(int64(id), 10)
}
