// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridorders

import (
	"time"
)

type Output struct {
	Duration      int64     `json:"duration"`
	Escrow        *float64  `json:"escrow"`
	IsBuyOrder    *bool     `json:"is_buy_order"`
	IsCorporation bool      `json:"is_corporation"`
	Issued        time.Time `json:"issued"`
	LocationId    int64     `json:"location_id"`
	MinVolume     *int64    `json:"min_volume"`
	OrderId       int64     `json:"order_id"`
	Price         float64   `json:"price"`
	Range         string    `json:"range"`
	RegionId      int64     `json:"region_id"`
	TypeId        int64     `json:"type_id"`
	VolumeRemain  int64     `json:"volume_remain"`
	VolumeTotal   int64     `json:"volume_total"`
}
