// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationiddivisions

type Output struct {
	Hangar []Hangar `json:"hangar"`
	Wallet []Wallet `json:"wallet"`
}

type Hangar struct {
	Division *int64  `json:"division"`
	Name     *string `json:"name"`
}

type Wallet struct {
	Division *int64  `json:"division"`
	Name     *string `json:"name"`
}
