// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridfittings

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Character   character.Identifier `path:"character_id"`
	Description string               `body:"json"`
	Items       []Items              `body:"json"`
	Name        string               `body:"json"`
	ShipTypeId  int64                `body:"json"`
}

type Items struct {
	Flag     string `json:"flag"`
	Quantity int64  `json:"quantity"`
	TypeId   int64  `json:"type_id"`
}
