// Code generated by cmd/generate-request; DO NOT EDIT.

package getincursions

type Output struct {
	ConstellationId      int64   `json:"constellation_id"`
	FactionId            int64   `json:"faction_id"`
	HasBoss              bool    `json:"has_boss"`
	InfestedSolarSystems []int64 `json:"infested_solar_systems"`
	Influence            float64 `json:"influence"`
	StagingSolarSystemId int64   `json:"staging_solar_system_id"`
	State                string  `json:"state"`
	Type                 string  `json:"type"`
}
