// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidwalletsdivisiontransactions

import (
	"time"
)

type Output struct {
	ClientId      int64     `json:"client_id"`
	Date          time.Time `json:"date"`
	IsBuy         bool      `json:"is_buy"`
	JournalRefId  int64     `json:"journal_ref_id"`
	LocationId    int64     `json:"location_id"`
	Quantity      int64     `json:"quantity"`
	TransactionId int64     `json:"transaction_id"`
	TypeId        int64     `json:"type_id"`
	UnitPrice     float64   `json:"unit_price"`
}
