// Code generated by cmd/generate-request; DO NOT EDIT.

package putfleetsfleetid

type Input struct {
	FleetId    int64   `path:"fleet_id"`
	IsFreeMove *bool   `body:"json"`
	Motd       *string `body:"json"`
}
