// Code generated by cmd/generate-request; DO NOT EDIT.

package getkillmailskillmailidkillmailhash

type Input struct {
	KillmailHash string `path:"killmail_hash"`
	KillmailId   int64  `path:"killmail_id"`
}
