// Code generated by cmd/generate-request; DO NOT EDIT.

package getkillmailskillmailidkillmailhash

import (
	"time"
)

type Output struct {
	Attackers     []Attackers `json:"attackers"`
	KillmailId    int64       `json:"killmail_id"`
	KillmailTime  time.Time   `json:"killmail_time"`
	MoonId        *int64      `json:"moon_id"`
	SolarSystemId int64       `json:"solar_system_id"`
	Victim        Victim      `json:"victim"`
	WarId         *int64      `json:"war_id"`
}

type Attackers struct {
	AllianceId     *int64  `json:"alliance_id"`
	CharacterId    *int64  `json:"character_id"`
	CorporationId  *int64  `json:"corporation_id"`
	DamageDone     int64   `json:"damage_done"`
	FactionId      *int64  `json:"faction_id"`
	FinalBlow      bool    `json:"final_blow"`
	SecurityStatus float64 `json:"security_status"`
	ShipTypeId     *int64  `json:"ship_type_id"`
	WeaponTypeId   *int64  `json:"weapon_type_id"`
}

type Items struct {
	Flag              int64   `json:"flag"`
	ItemTypeId        int64   `json:"item_type_id"`
	QuantityDestroyed *int64  `json:"quantity_destroyed"`
	QuantityDropped   *int64  `json:"quantity_dropped"`
	Singleton         int64   `json:"singleton"`
	Items             []Items `json:"items"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

type Victim struct {
	AllianceId    *int64    `json:"alliance_id"`
	CharacterId   *int64    `json:"character_id"`
	CorporationId *int64    `json:"corporation_id"`
	DamageTaken   int64     `json:"damage_taken"`
	FactionId     *int64    `json:"faction_id"`
	Items         []Items   `json:"items"`
	Position      *Position `json:"position"`
	ShipTypeId    int64     `json:"ship_type_id"`
}
