// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcorporationhistory

import (
	"time"
)

type Output struct {
	CorporationId int64     `json:"corporation_id"`
	IsDeleted     *bool     `json:"is_deleted"`
	RecordId      int64     `json:"record_id"`
	StartDate     time.Time `json:"start_date"`
}
