// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidroleshistory

import (
	"time"
)

type Output struct {
	ChangedAt   time.Time `json:"changed_at"`
	CharacterId int64     `json:"character_id"`
	IssuerId    int64     `json:"issuer_id"`
	NewRoles    []string  `json:"new_roles"`
	OldRoles    []string  `json:"old_roles"`
	RoleType    string    `json:"role_type"`
}
