// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridassetslocations

type Output struct {
	ItemId   int64    `json:"item_id"`
	Position Position `json:"position"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
