// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsprojectscontribution

import (
	"time"
)

type Output struct {
	Contributed  int64      `json:"contributed"`
	LastModified *time.Time `json:"last_modified"`
}
