// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridship

type Output struct {
	ShipItemId int64  `json:"ship_item_id"`
	ShipName   string `json:"ship_name"`
	ShipTypeId int64  `json:"ship_type_id"`
}
