// Code generated by cmd/generate-request; DO NOT EDIT.

package getalliancesallianceidcontacts

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](http.MethodGet, "/alliances/{alliance_id}/contacts")
