// Code generated by cmd/generate-request; DO NOT EDIT.

package getalliancesallianceidcontactslabels

import (
	"github.com/xaroth/lib-esi-go/common/alliance"
)

type Input struct {
	Alliance alliance.Identifier `path:"alliance_id"`
}
