// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridfwstats

import (
	"time"
)

type Output struct {
	CurrentRank   *int64        `json:"current_rank"`
	EnlistedOn    *time.Time    `json:"enlisted_on"`
	FactionId     *int64        `json:"faction_id"`
	HighestRank   *int64        `json:"highest_rank"`
	Kills         Kills         `json:"kills"`
	VictoryPoints VictoryPoints `json:"victory_points"`
}

type Kills struct {
	LastWeek  int64 `json:"last_week"`
	Total     int64 `json:"total"`
	Yesterday int64 `json:"yesterday"`
}

type VictoryPoints struct {
	LastWeek  int64 `json:"last_week"`
	Total     int64 `json:"total"`
	Yesterday int64 `json:"yesterday"`
}
