// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversecategoriescategoryid

type Output struct {
	CategoryId int64   `json:"category_id"`
	Groups     []int64 `json:"groups"`
	Name       string  `json:"name"`
	Published  bool    `json:"published"`
}
