// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridwalletjournal

import (
	"time"
)

type Output struct {
	Amount        *float64  `json:"amount"`
	Balance       *float64  `json:"balance"`
	ContextId     *int64    `json:"context_id"`
	ContextIdType *string   `json:"context_id_type"`
	Date          time.Time `json:"date"`
	Description   string    `json:"description"`
	FirstPartyId  *int64    `json:"first_party_id"`
	Id            int64     `json:"id"`
	Reason        *string   `json:"reason"`
	RefType       string    `json:"ref_type"`
	SecondPartyId *int64    `json:"second_party_id"`
	Tax           *float64  `json:"tax"`
	TaxReceiverId *int64    `json:"tax_receiver_id"`
}
