// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridfatigue

import (
	"time"
)

type Output struct {
	JumpFatigueExpireDate *time.Time `json:"jump_fatigue_expire_date"`
	LastJumpDate          *time.Time `json:"last_jump_date"`
	LastUpdateDate        *time.Time `json:"last_update_date"`
}
