// Code generated by cmd/generate-request; DO NOT EDIT.

package getfleetsfleetidwings

type Output struct {
	Id     int64    `json:"id"`
	Name   string   `json:"name"`
	Squads []Squads `json:"squads"`
}

type Squads struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
