// Code generated by cmd/generate-request; DO NOT EDIT.

package getdogmadynamicitemstypeiditemid

type Output struct {
	CreatedBy       int64             `json:"created_by"`
	DogmaAttributes []DogmaAttributes `json:"dogma_attributes"`
	DogmaEffects    []DogmaEffects    `json:"dogma_effects"`
	MutatorTypeId   int64             `json:"mutator_type_id"`
	SourceTypeId    int64             `json:"source_type_id"`
}

type DogmaAttributes struct {
	AttributeId int64   `json:"attribute_id"`
	Value       float64 `json:"value"`
}

type DogmaEffects struct {
	EffectId  int64 `json:"effect_id"`
	IsDefault bool  `json:"is_default"`
}
