// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmailmailid

import (
	"time"
)

type Output struct {
	Body       *string      `json:"body"`
	From       *int64       `json:"from"`
	Labels     []int64      `json:"labels"`
	Read       *bool        `json:"read"`
	Recipients []Recipients `json:"recipients"`
	Subject    *string      `json:"subject"`
	Timestamp  *time.Time   `json:"timestamp"`
}

type Recipients struct {
	RecipientId   int64  `json:"recipient_id"`
	RecipientType string `json:"recipient_type"`
}
