// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidmembertracking

import (
	"time"
)

type Output struct {
	BaseId      *int64     `json:"base_id"`
	CharacterId int64      `json:"character_id"`
	LocationId  *int64     `json:"location_id"`
	LogoffDate  *time.Time `json:"logoff_date"`
	LogonDate   *time.Time `json:"logon_date"`
	ShipTypeId  *int64     `json:"ship_type_id"`
	StartDate   *time.Time `json:"start_date"`
}
