// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuressovereigntyhubslisting

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](http.MethodGet, "/corporations/{corporation_id}/structures/sovereignty-hubs")
