// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xaroth/lib-esi-go/request (interfaces: DefaultsProvider)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination mock/mock_defaults_provider.go -package mock github.com/xaroth/lib-esi-go/request DefaultsProvider
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	config "github.com/xaroth/lib-esi-go/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockDefaultsProvider is a mock of DefaultsProvider interface.
type MockDefaultsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultsProviderMockRecorder
	isgomock struct{}
}

// MockDefaultsProviderMockRecorder is the mock recorder for MockDefaultsProvider.
type MockDefaultsProviderMockRecorder struct {
	mock *MockDefaultsProvider
}

// NewMockDefaultsProvider creates a new mock instance.
func NewMockDefaultsProvider(ctrl *gomock.Controller) *MockDefaultsProvider {
	mock := &MockDefaultsProvider{ctrl: ctrl}
	mock.recorder = &MockDefaultsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultsProvider) EXPECT() *MockDefaultsProviderMockRecorder {
	return m.recorder
}

// DefaultRequestConfig mocks base method.
func (m *MockDefaultsProvider) DefaultRequestConfig() *config.Defaults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultRequestConfig")
	ret0, _ := ret[0].(*config.Defaults)
	return ret0
}

// DefaultRequestConfig indicates an expected call of DefaultRequestConfig.
func (mr *MockDefaultsProviderMockRecorder) DefaultRequestConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultRequestConfig", reflect.TypeOf((*MockDefaultsProvider)(nil).DefaultRequestConfig))
}

// Do mocks base method.
func (m *MockDefaultsProvider) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockDefaultsProviderMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDefaultsProvider)(nil).Do), req)
}
