// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xaroth/lib-esi-go/request (interfaces: SchedulingSender)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination mock/mock_sender.go -package mock github.com/xaroth/lib-esi-go/request SchedulingSender
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	request "github.com/xaroth/lib-esi-go/request"
	gomock "go.uber.org/mock/gomock"
)

// MockSchedulingSender is a mock of SchedulingSender interface.
type MockSchedulingSender struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulingSenderMockRecorder
	isgomock struct{}
}

// MockSchedulingSenderMockRecorder is the mock recorder for MockSchedulingSender.
type MockSchedulingSenderMockRecorder struct {
	mock *MockSchedulingSender
}

// NewMockSchedulingSender creates a new mock instance.
func NewMockSchedulingSender(ctrl *gomock.Controller) *MockSchedulingSender {
	mock := &MockSchedulingSender{ctrl: ctrl}
	mock.recorder = &MockSchedulingSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulingSender) EXPECT() *MockSchedulingSenderMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockSchedulingSender) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockSchedulingSenderMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockSchedulingSender)(nil).Do), req)
}

// Schedule mocks base method.
func (m *MockSchedulingSender) Schedule(ctx context.Context, info request.RequestInfo, token request.Token) (func(*http.Response), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", ctx, info, token)
	ret0, _ := ret[0].(func(*http.Response))
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Schedule indicates an expected call of Schedule.
func (mr *MockSchedulingSenderMockRecorder) Schedule(ctx, info, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockSchedulingSender)(nil).Schedule), ctx, info, token)
}
