// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcalendareventidattendees

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	EventId   int64                `path:"event_id"`
}
