// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcalendareventidattendees

type Output struct {
	CharacterId   *int64  `json:"character_id"`
	EventResponse *string `json:"event_response"`
}
