// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidtitles

type Output struct {
	GrantableRoles        []string `json:"grantable_roles"`
	GrantableRolesAtBase  []string `json:"grantable_roles_at_base"`
	GrantableRolesAtHq    []string `json:"grantable_roles_at_hq"`
	GrantableRolesAtOther []string `json:"grantable_roles_at_other"`
	Name                  *string  `json:"name"`
	Roles                 []string `json:"roles"`
	RolesAtBase           []string `json:"roles_at_base"`
	RolesAtHq             []string `json:"roles_at_hq"`
	RolesAtOther          []string `json:"roles_at_other"`
	TitleId               *int64   `json:"title_id"`
}
