// Code generated by cmd/generate-request; DO NOT EDIT.

package getstatus

import (
	"time"
)

type Output struct {
	Players       int64     `json:"players"`
	ServerVersion string    `json:"server_version"`
	StartTime     time.Time `json:"start_time"`
	Vip           *bool     `json:"vip"`
}
