// Code generated by cmd/generate-request; DO NOT EDIT.

package getfwsystems

type Output struct {
	Contested              string `json:"contested"`
	OccupierFactionId      int64  `json:"occupier_faction_id"`
	OwnerFactionId         int64  `json:"owner_faction_id"`
	SolarSystemId          int64  `json:"solar_system_id"`
	VictoryPoints          int64  `json:"victory_points"`
	VictoryPointsThreshold int64  `json:"victory_points_threshold"`
}
