// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidmemberstitles

type Output struct {
	CharacterId int64   `json:"character_id"`
	Titles      []int64 `json:"titles"`
}
