// Code generated by cmd/generate-request; DO NOT EDIT.

package getdogmaattributes

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.CreateStatic[Output](
	http.MethodGet,
	"/dogma/attributes",
)
