// Code generated by cmd/generate-request; DO NOT EDIT.

package getsovereigntycampaigns

import (
	"time"
)

type Output struct {
	AttackersScore  *float64       `json:"attackers_score"`
	CampaignId      int64          `json:"campaign_id"`
	ConstellationId int64          `json:"constellation_id"`
	DefenderId      *int64         `json:"defender_id"`
	DefenderScore   *float64       `json:"defender_score"`
	EventType       string         `json:"event_type"`
	Participants    []Participants `json:"participants"`
	SolarSystemId   int64          `json:"solar_system_id"`
	StartTime       time.Time      `json:"start_time"`
	StructureId     int64          `json:"structure_id"`
}

type Participants struct {
	AllianceId int64   `json:"alliance_id"`
	Score      float64 `json:"score"`
}
