// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniverseconstellationsconstellationid

type Output struct {
	ConstellationId int64    `json:"constellation_id"`
	Name            string   `json:"name"`
	Position        Position `json:"position"`
	RegionId        int64    `json:"region_id"`
	Systems         []int64  `json:"systems"`
}

type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}
