// Code generated by cmd/generate-request; DO NOT EDIT.

package getmarketsgroupsmarketgroupid

type Output struct {
	Description   string  `json:"description"`
	MarketGroupId int64   `json:"market_group_id"`
	Name          string  `json:"name"`
	ParentGroupId *int64  `json:"parent_group_id"`
	Types         []int64 `json:"types"`
}
