// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridplanets

import (
	"time"
)

type Output struct {
	LastUpdate    time.Time `json:"last_update"`
	NumPins       int64     `json:"num_pins"`
	OwnerId       int64     `json:"owner_id"`
	PlanetId      int64     `json:"planet_id"`
	PlanetType    string    `json:"planet_type"`
	SolarSystemId int64     `json:"solar_system_id"`
	UpgradeLevel  int64     `json:"upgrade_level"`
}
