// Code generated by cmd/generate-request; DO NOT EDIT.

package deletecharacterscharacteridcontacts

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](http.MethodDelete, "/characters/{character_id}/contacts")
