// Code generated by cmd/generate-request; DO NOT EDIT.

package getcontractspublicitemscontractid

type Output struct {
	IsBlueprintCopy    *bool  `json:"is_blueprint_copy"`
	IsIncluded         bool   `json:"is_included"`
	ItemId             *int64 `json:"item_id"`
	MaterialEfficiency *int64 `json:"material_efficiency"`
	Quantity           int64  `json:"quantity"`
	RecordId           int64  `json:"record_id"`
	Runs               *int64 `json:"runs"`
	TimeEfficiency     *int64 `json:"time_efficiency"`
	TypeId             int64  `json:"type_id"`
}
