// Code generated by cmd/generate-request; DO NOT EDIT.

package getparagonhubskinr

type Input struct {
	After  *string `query:"after"`
	Before *string `query:"before"`
	Limit  *int64  `query:"limit"`
}
