// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmaillabels

type Output struct {
	Labels           []Labels `json:"labels"`
	TotalUnreadCount *int64   `json:"total_unread_count"`
}

type Labels struct {
	Color       *string `json:"color"`
	LabelId     *int64  `json:"label_id"`
	Name        *string `json:"name"`
	UnreadCount *int64  `json:"unread_count"`
}
