// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidshareholders

type Output struct {
	ShareCount      int64  `json:"share_count"`
	ShareholderId   int64  `json:"shareholder_id"`
	ShareholderType string `json:"shareholder_type"`
}
