// Code generated by cmd/generate-request; DO NOT EDIT.

package getmarketsregionidorders

type Input struct {
	OrderType string `query:"order_type" required:"true"`
	Page      *int32 `query:"page"`
	RegionId  int64  `path:"region_id"`
	TypeId    *int64 `query:"type_id"`
}
