// Code generated by cmd/generate-request; DO NOT EDIT.

package getmarketsregionidorders

import (
	"time"
)

type Output struct {
	Duration     int64     `json:"duration"`
	IsBuyOrder   bool      `json:"is_buy_order"`
	Issued       time.Time `json:"issued"`
	LocationId   int64     `json:"location_id"`
	MinVolume    int64     `json:"min_volume"`
	OrderId      int64     `json:"order_id"`
	Price        float64   `json:"price"`
	Range        string    `json:"range"`
	SystemId     int64     `json:"system_id"`
	TypeId       int64     `json:"type_id"`
	VolumeRemain int64     `json:"volume_remain"`
	VolumeTotal  int64     `json:"volume_total"`
}
