// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridsearch

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Categories []string             `query:"categories"`
	Character  character.Identifier `path:"character_id"`
	Search     string               `query:"search"`
	Strict     *bool                `query:"strict"`
}
