// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridsearch

type Output struct {
	Agent         []int64 `json:"agent"`
	Alliance      []int64 `json:"alliance"`
	Character     []int64 `json:"character"`
	Constellation []int64 `json:"constellation"`
	Corporation   []int64 `json:"corporation"`
	Faction       []int64 `json:"faction"`
	InventoryType []int64 `json:"inventory_type"`
	Region        []int64 `json:"region"`
	SolarSystem   []int64 `json:"solar_system"`
	Station       []int64 `json:"station"`
	Structure     []int64 `json:"structure"`
}
