// Code generated by cmd/generate-request; DO NOT EDIT.

package getcontractspublicregionid

import (
	"time"
)

type Output struct {
	Buyout              *float64  `json:"buyout"`
	Collateral          *float64  `json:"collateral"`
	ContractId          int64     `json:"contract_id"`
	DateExpired         time.Time `json:"date_expired"`
	DateIssued          time.Time `json:"date_issued"`
	DaysToComplete      *int64    `json:"days_to_complete"`
	EndLocationId       *int64    `json:"end_location_id"`
	ForCorporation      *bool     `json:"for_corporation"`
	IssuerCorporationId int64     `json:"issuer_corporation_id"`
	IssuerId            int64     `json:"issuer_id"`
	Price               *float64  `json:"price"`
	Reward              *float64  `json:"reward"`
	StartLocationId     *int64    `json:"start_location_id"`
	Title               *string   `json:"title"`
	Type                string    `json:"type"`
	Volume              *float64  `json:"volume"`
}
