// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridmaillabels

import (
	"github.com/xaroth/lib-esi-go/common/character"
)

type Input struct {
	Character character.Identifier `path:"character_id"`
	Color     *string              `body:"json"`
	Name      string               `body:"json"`
}
