// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridloyaltypoints

type Output struct {
	CorporationId int64 `json:"corporation_id"`
	LoyaltyPoints int64 `json:"loyalty_points"`
}
