// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidfacilities

type Output struct {
	FacilityId int64 `json:"facility_id"`
	SystemId   int64 `json:"system_id"`
	TypeId     int64 `json:"type_id"`
}
