// Code generated by cmd/generate-request; DO NOT EDIT.

package postcharacterscharacteridcontacts

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, Output](http.MethodPost, "/characters/{character_id}/contacts")
