// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationscorporationidassets

type Output struct {
	IsBlueprintCopy *bool  `json:"is_blueprint_copy"`
	IsSingleton     bool   `json:"is_singleton"`
	ItemId          int64  `json:"item_id"`
	LocationFlag    string `json:"location_flag"`
	LocationId      int64  `json:"location_id"`
	LocationType    string `json:"location_type"`
	Quantity        int64  `json:"quantity"`
	TypeId          int64  `json:"type_id"`
}
