// Code generated by cmd/generate-request; DO NOT EDIT.

package getcorporationsstructuresskyhookslisting

import (
	"github.com/xaroth/lib-esi-go/common/item"
	"github.com/xaroth/lib-esi-go/common/planet"
)

type Output struct {
	Skyhooks []CorporationsStructuresSkyhooksListingSkyhook `json:"skyhooks"`
}

type CorporationsStructuresSkyhooksListingSkyhook struct {
	Id     item.Identifier   `json:"id"`
	Planet planet.Identifier `json:"planet_id"`
}
