// Code generated by cmd/generate-request; DO NOT EDIT.

package getfwleaderboardscorporations

type Output struct {
	Kills         Kills         `json:"kills"`
	VictoryPoints VictoryPoints `json:"victory_points"`
}

type ActiveTotal struct {
	Amount        *int64 `json:"amount"`
	CorporationId *int64 `json:"corporation_id"`
}

type LastWeek struct {
	Amount        *int64 `json:"amount"`
	CorporationId *int64 `json:"corporation_id"`
}

type Yesterday struct {
	Amount        *int64 `json:"amount"`
	CorporationId *int64 `json:"corporation_id"`
}

type Kills struct {
	ActiveTotal []ActiveTotal `json:"active_total"`
	LastWeek    []LastWeek    `json:"last_week"`
	Yesterday   []Yesterday   `json:"yesterday"`
}

type VictoryPoints struct {
	ActiveTotal []ActiveTotal `json:"active_total"`
	LastWeek    []LastWeek    `json:"last_week"`
	Yesterday   []Yesterday   `json:"yesterday"`
}
