// Code generated by cmd/generate-request; DO NOT EDIT.

package getfwleaderboardscorporations

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.CreateStatic[*Output](
	http.MethodGet,
	"/fw/leaderboards/corporations",
)
