// Code generated by cmd/generate-request; DO NOT EDIT.

package postroute

import (
	"github.com/xaroth/lib-esi-go/common/solarsystem"
)

type Input struct {
	OriginSystem      solarsystem.Identifier   `path:"origin_system_id"`
	DestinationSystem solarsystem.Identifier   `path:"destination_system_id"`
	AvoidSystems      []solarsystem.Identifier `body:"json"`
	Connections       []RouteConnection        `body:"json"`
	Preference        *string                  `body:"json"`
	SecurityPenalty   *int64                   `body:"json"`
}

type RouteConnection struct {
	From solarsystem.Identifier `json:"from"`
	To   solarsystem.Identifier `json:"to"`
}
