// Code generated by cmd/generate-request; DO NOT EDIT.

package postuiopenwindowinformation

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, struct{}](http.MethodPost, "/ui/openwindow/information")
