// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridmail

import (
	"time"
)

type Output struct {
	From       *int64       `json:"from"`
	IsRead     *bool        `json:"is_read"`
	Labels     []int64      `json:"labels"`
	MailId     *int64       `json:"mail_id"`
	Recipients []Recipients `json:"recipients"`
	Subject    *string      `json:"subject"`
	Timestamp  *time.Time   `json:"timestamp"`
}

type Recipients struct {
	RecipientId   int64  `json:"recipient_id"`
	RecipientType string `json:"recipient_type"`
}
