// Code generated by cmd/generate-request; DO NOT EDIT.

package getmilitarycampaignsdetail

import (
	"github.com/xaroth/lib-esi-go/common/uuid"
)

type Input struct {
	CampaignId uuid.UUID `path:"campaign_id"`
}
