// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcalendareventid

import (
	"time"
)

type Output struct {
	Date       time.Time `json:"date"`
	Duration   int64     `json:"duration"`
	EventId    int64     `json:"event_id"`
	Importance int64     `json:"importance"`
	OwnerId    int64     `json:"owner_id"`
	OwnerName  string    `json:"owner_name"`
	OwnerType  string    `json:"owner_type"`
	Response   string    `json:"response"`
	Text       string    `json:"text"`
	Title      string    `json:"title"`
}
