// Code generated by cmd/generate-request; DO NOT EDIT.

package getfwstats

type Output struct {
	FactionId         int64         `json:"faction_id"`
	Kills             Kills         `json:"kills"`
	Pilots            int64         `json:"pilots"`
	SystemsControlled int64         `json:"systems_controlled"`
	VictoryPoints     VictoryPoints `json:"victory_points"`
}

type Kills struct {
	LastWeek  int64 `json:"last_week"`
	Total     int64 `json:"total"`
	Yesterday int64 `json:"yesterday"`
}

type VictoryPoints struct {
	LastWeek  int64 `json:"last_week"`
	Total     int64 `json:"total"`
	Yesterday int64 `json:"yesterday"`
}
