// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversetypestypeid

type Output struct {
	Capacity        *float64          `json:"capacity"`
	Description     string            `json:"description"`
	DogmaAttributes []DogmaAttributes `json:"dogma_attributes"`
	DogmaEffects    []DogmaEffects    `json:"dogma_effects"`
	GraphicId       *int64            `json:"graphic_id"`
	GroupId         int64             `json:"group_id"`
	IconId          *int64            `json:"icon_id"`
	MarketGroupId   *int64            `json:"market_group_id"`
	Mass            *float64          `json:"mass"`
	Name            string            `json:"name"`
	PackagedVolume  *float64          `json:"packaged_volume"`
	PortionSize     *int64            `json:"portion_size"`
	Published       bool              `json:"published"`
	Radius          *float64          `json:"radius"`
	TypeId          int64             `json:"type_id"`
	Volume          *float64          `json:"volume"`
}

type DogmaAttributes struct {
	AttributeId int64   `json:"attribute_id"`
	Value       float64 `json:"value"`
}

type DogmaEffects struct {
	EffectId  int64 `json:"effect_id"`
	IsDefault bool  `json:"is_default"`
}
