// Code generated by cmd/generate-request; DO NOT EDIT.

package postcorporationscorporationidassetsnames

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, []*Output](http.MethodPost, "/corporations/{corporation_id}/assets/names")
