// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridcontacts

type Output struct {
	ContactId   int64   `json:"contact_id"`
	ContactType string  `json:"contact_type"`
	IsBlocked   *bool   `json:"is_blocked"`
	IsWatched   *bool   `json:"is_watched"`
	LabelIds    []int64 `json:"label_ids"`
	Standing    float64 `json:"standing"`
}
