// Code generated by cmd/generate-request; DO NOT EDIT.

package getuniversebloodlines

type Output struct {
	BloodlineId   int64  `json:"bloodline_id"`
	Charisma      int64  `json:"charisma"`
	CorporationId int64  `json:"corporation_id"`
	Description   string `json:"description"`
	Intelligence  int64  `json:"intelligence"`
	Memory        int64  `json:"memory"`
	Name          string `json:"name"`
	Perception    int64  `json:"perception"`
	RaceId        int64  `json:"race_id"`
	ShipTypeId    int64  `json:"ship_type_id"`
	Willpower     int64  `json:"willpower"`
}
