// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscosmeticsskinrcomponents

type Output struct {
	Licenses []CharactersCosmeticsSkinrComponentsItem `json:"licenses"`
}

type Run struct {
	Remaining *int64 `json:"remaining,omitempty"`
	Unlimited *bool  `json:"unlimited,omitempty"`
}

type CharactersCosmeticsSkinrComponentsItem struct {
	ComponentId int64  `json:"component_id"`
	Runs        Run    `json:"runs"`
	Type        string `json:"type"`
}
