// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridattributes

import (
	"time"
)

type Output struct {
	AccruedRemapCooldownDate *time.Time `json:"accrued_remap_cooldown_date"`
	BonusRemaps              *int64     `json:"bonus_remaps"`
	Charisma                 int64      `json:"charisma"`
	Intelligence             int64      `json:"intelligence"`
	LastRemapDate            *time.Time `json:"last_remap_date"`
	Memory                   int64      `json:"memory"`
	Perception               int64      `json:"perception"`
	Willpower                int64      `json:"willpower"`
}
