// Code generated by cmd/generate-request; DO NOT EDIT.

package getcharacterscharacteridattributes

import (
	"net/http"

	"github.com/xaroth/lib-esi-go/request"
)

var Request = request.Create[Input, *Output](http.MethodGet, "/characters/{character_id}/attributes")
